[alembic]
script_location = migrations
prepend_sys_path = .
version_path_separator = os
sqlalchemy.url = postgresql+asyncpg://user:password@postgres:5432/codereviewer

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers] # Decides where logs go ( goes to consolse instead of file)
keys = console

[formatters] # Controls what log messages look like.
keys = generic

[logger_root] # Only show warnings or errors
level = WARN
handlers = console
qualname =

[logger_sqlalchemy] # Level of logging that has to be shown
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic] # Alembic prints useful migration information.
level = INFO
handlers =
qualname = alembic

[handler_console] # Print logs to terminal using the standard error stream (stderr)
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic


[formatter_generic] # logs formatter
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S